language: node_js
node_js:
  - "4.1"
before_script:
  - npm install
  - npm install -g codeclimate-test-reporter
  - npm install -g jscover
script: gulp
after_script: codeclimate-test-reporter < coverage.lcov
